[phases.setup]
nixPkgs = ["nodejs", "python39", "python39Packages.pip"]

[phases.install]
cmds = [
  "cd frontend && npm ci",
  "cd backend && python -m ensurepip --upgrade && python -m pip install -r requirements.txt"
]

[phases.build]  
cmds = ["cd frontend && CI=false npm run build"]

[start]
cmd = "cd backend && python app.py"

[variables]
NODE_ENV = "production"
PYTHON_VERSION = "3.9"