[phases.setup]
nixPkgs = ["nodejs", "python39", "gcc"]

[phases.install]
cmds = [
  "cd frontend && npm ci",
  "cd backend && pip install -r requirements.txt"
]

[phases.build]  
cmds = ["cd frontend && CI=false npm run build"]

[start]
cmd = "cd backend && python app.py"

[variables]
NODE_ENV = "production"
NIXPACKS_PYTHON_VERSION = "3.9"